name: release

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: pom.yml バージョン更新
      run:  mvn versions:set -DnewVersion=$(git rev-parse --short HEAD)
    - name: Mavenを使ってビルド
      run:  mvn -B package
    - name: original-*.jarを削除
      run:  rm target/original-*.jar
    - name: パッケージをビルドの成果物としてリリース
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-v${{ github.run_number }}
        files: target/*.jar
